<template functional>
  <div class="table-wrapper">
    <h2>声母</h2>
    <table>
      <tr>
        <th></th>
        <th>b</th><th>p</th><th>m</th><th>f</th><th>d</th><th>t</th><th>n</th><th>l</th><th>sl</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/p/</td><td>/pʰ/</td><td>/m/</td><td>/f/</td><td>/t/</td><td>/tʰ/</td><td>/n/</td><td>/l/</td><td>/ɬ/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>波</td><td>坡</td><td>摸</td><td>科</td><td>多</td><td>拖</td><td>挪</td><td>罗</td><td>锁</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>g</th><th>k</th><th>gw</th><th>kw</th><th>ng</th><th>h</th><th>z</th><th>c</th><th>s</th><th>nj</th><th>j</th><th>w</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/k/</td><td>/kʰ/</td><td>/kʷ/</td><td>/kʷʰ/</td><td>/ŋ/</td><td>/h/</td><td>/tʃ/</td><td>/tʃʰ/</td><td>/ʃ/</td><td>/ɳ/</td><td>/j/</td><td>/ʋ/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>哥</td><td>柯</td><td>光</td><td>框</td><td>我</td><td>可</td><td>左</td><td>错</td><td>所</td><td>日</td><td>也</td><td>话</td>
      </tr>
    </table>
    <h2>韵母</h2>
    <table>
      <tr>
        <th></th>
        <th>aa</th><th>aai</th><th>aau</th><th>aam</th><th>aan</th><th>aang</th><th>aap</th><th>aat</th><th>aak</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/a/</td><td>/ai/</td><td>/au/</td><td>/am/</td><td>/an/</td><td>/aŋ/</td><td>/ap/</td><td>/at/</td><td>/ak/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>渣</td><td>斋</td><td>罩</td><td>湛</td><td>赞</td><td>争</td><td>杂</td><td>扎</td><td>责</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th></th><th>ai</th><th>au</th><th>am</th><th>an</th><th>ang</th><th>ap</th><th>at</th><th>ak</th>
      </tr>
      <tr>
        <th>音标</th>
        <td></td><td>/ɐi/</td><td>/ɐu/</td><td>/ɐm/</td><td>/ɐn/</td><td>/ɐŋ/</td><td>/ɐp/</td><td>/ɐt/</td><td>/ɐk/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td></td><td>制</td><td>走</td><td>针</td><td>真</td><td>铮</td><td>集</td><td>窒</td><td>则</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>e</th><th>ei</th><th>iau</th><th>iam</th><th>ian</th><th>iang</th><th>iap</th><th>iat</th><th>iak</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/ɛ/</td><td>/ei/</td><td>/iɐu/</td><td>/iɐm/</td><td>/iɐn/</td><td>/iɐŋ/</td><td>/iɐp/</td><td>/iɐt/</td><td>/iɐk/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>姐</td><td>四</td><td>猫</td><td>点</td><td>片</td><td>张</td><td>夹</td><td>裂</td><td>着</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>i</th><th></th><th>iu</th><th>im</th><th>in</th><th>ing</th><th>ip</th><th>it</th><th>ik</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/i/</td><td></td><td>/iu/</td><td>/im/</td><td>/in/</td><td>/eŋ/</td><td>/ip/</td><td>/it/</td><td>/ek/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>资</td><td></td><td>招</td><td>尖</td><td>箭</td><td>正</td><td>接</td><td>节</td><td>直</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>o</th><th>oi</th><th>ou</th><th></th><th>on</th><th>ong</th><th></th><th>ot</th><th>ok</th>
      </tr>
      <tr>
        <th>音标</th><td>/ɔ/</td><td>/uɔi/</td><td>/ɔu/</td><td></td><td>/uɔn/</td><td>/uɔŋ/</td><td></td><td>/uɔt/</td><td>/uɔk/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>左</td><td>再</td><td>做</td><td></td><td>安</td><td>庄</td><td></td><td>割</td><td>捉</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>u</th><th>ui</th><th></th><th></th><th>un</th><th>ung</th><th></th><th>ut</th><th>uk</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/u/</td><td>/ui/</td><td></td><td></td><td>/un/</td><td>/uŋ/</td><td></td><td>/ut/</td><td>/uk/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>乌</td><td>最</td><td></td><td></td><td>换</td><td>中</td><td></td><td>活</td><td>足</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>yu</th><th>ng</th><th></th><th></th><th>yun</th><th></th><th></th><th>yut</th><th></th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/y/</td><td>/ŋ/</td><td></td><td></td><td>/yn/</td><td></td><td></td><td>/yt/</td><td></td>
      </tr>
      <tr>
        <th>例字</th>
        <td>与</td><td>五</td><td></td><td></td><td>渊</td><td></td><td></td><td>越</td><td></td>
      </tr>
    </table>
    <h2>声调</h2>
    <table>
      <tr>
        <th></th>
        <th>阴平</th><th>阴入</th><th>阴上</th><th>阴去</th><th>中入</th><th>阳平</th><th>阳上</th><th>阳去</th><th>阳入</th>
      </tr>
      <tr>
        <th>记号</th>
        <td colspan='2'>1</td><td>2</td><td colspan='2'>3</td><td>4</td><td>5</td><td colspan='2'>6</td>
      </tr>
      <tr>
        <th>调值</th>
        <td>55</td><td>5</td><td>35</td><td>33</td><td>3</td><td>11</td><td>23</td><td>22</td><td>2</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>分</td><td>忽</td><td>粉</td><td>训</td><td>法</td><td>焚</td><td>愤</td><td>份</td><td>佛</td>
      </tr>
    </table>
  </div>
</template>
