<template>
  <div class="table-wrapper">
    <h2>声母</h2>
    <table>
      <tr>
        <th></th>
        <th>b</th><th>p</th><th>m</th><th>w</th><th>d</th><th>t</th><th>n</th><th>l</th><th>sl</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/p/</td><td>/pʰ/</td><td>/m/</td><td>/w/</td><td>/t/</td><td>/tʰ/</td><td>/n/</td><td>/l/</td><td>/ɬ/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>波</td><td>坡</td><td>摸</td><td>我</td><td>刀</td><td>桃</td><td>挪</td><td>罗</td><td>所</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>g</th><th>k</th><th>ng</th><th>h</th><th>z</th><th>c</th><th>nj</th><th>j</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/k/</td><td>/kʰ/</td><td>/ŋ/</td><td>/h/</td><td>/ts/</td><td>/tsʰ/</td><td>/ɳ/</td><td>/j/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>稿</td><td>可</td><td>卧</td><td>好</td><td>左</td><td>错</td><td>让</td><td>二</td>
      </tr>
    </table>
    <h2>韵母</h2>
    <table>
      <tr>
        <th></th>
        <th></th><th>a</th><th>o</th><th>e</th><th>ai</th><th>oi</th><th>au</th><th>eu</th><th>am</th><th>em</th><th>an</th><th>en</th><th>ang</th><th>ong</th>
      </tr>
      <tr>
        <th>音标</th>
        <td></td><td>/a/</td><td>/ɔ/</td><td>/ɛ/</td><td>/ai/</td><td>/oi/</td><td>/au/</td><td>/eu/</td><td>/am/</td><td>/em/</td><td>/an/</td><td>/en/</td><td>/aŋ/</td><td>/oŋ/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td></td><td>亚</td><td>学</td><td>哑</td><td>闲</td><td>鞋</td><td>奥</td><td>乌</td><td>暗</td><td>醮</td><td>按</td><td>应</td><td>红</td><td>中</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>i</th><th>ia</th><th>io</th><th></th><th></th><th></th><th>iau</th><th>iu</th><th>iam</th><th>im</th><th></th><th>in</th><th>iang</th><th>iong</th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/i/</td><td>/ia/</td><td>/io/</td><td></td><td></td><td></td><td>/iau/</td><td>/iu/</td><td>/iam/</td><td>/im/</td><td></td><td>/in/</td><td>/iaŋ/</td><td>/ioŋ/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>医</td><td>营</td><td>腰</td><td></td><td></td><td></td><td>忧</td><td>油</td><td>厌</td><td>音</td><td></td><td>因</td><td>央</td><td>啄</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <th>u</th><th>ua</th><th></th><th>ue</th><th>uai</th><th>ui</th><th>uau</th><th></th><th>uam</th><th></th><th>uan</th><th>un</th><th>uang</th><th></th>
      </tr>
      <tr>
        <th>音标</th>
        <td>/u/</td><td>/ua/</td><td></td><td>/uɛ/</td><td>/uai/</td><td>/ui/</td><td>/uau/</td><td></td><td>/uam/</td><td></td><td>/uan/</td><td>/un/</td><td>/uaŋ/</td><td></td>
      </tr>
      <tr>
        <th>例字</th>
        <td>有</td><td>碗</td><td></td><td>话</td><td>坏</td><td>位</td><td>否</td><td></td><td>犯</td><td></td><td>湾</td><td>温</td><td>往</td><td></td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <td></td><th>ap</th><th>ep</th><th>at</th><th>et</th><th>ak</th><th>ok</th>
      </tr>
      <tr>
        <th>音标</th>
        <td></td><td>/ap/</td><td>/ep/</td><td>/at/</td><td>/et/</td><td>/ak/</td><td>/ok/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td></td><td>盒</td><td>辑</td><td>压</td><td>益</td><td>六</td><td>恶</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <td></td><th>iap</th><th>ip</th><th></th><th>it</th><th>iak</th><th>iok</th>
      </tr>
      <tr>
        <th>音标</th>
        <td></td><td>/iap/</td><td>/ip/</td><td></td><td>/it/</td><td>/iak/</td><td>/iok/</td>
      </tr>
      <tr>
        <th>例字</th>
        <td></td><td>叶</td><td>肉</td><td></td><td>乙</td><td>弱</td><td>约</td>
      </tr>
    </table>
    <table>
      <tr>
        <th></th>
        <td></td><th>uap</th><th></th><th>uat</th><th>ut</th><th>uak</th><th></th>
      </tr>
      <tr>
        <th>音标</th>
        <td></td><td>/uap/</td><td></td><td>/uat/</td><td>/ut/</td><td>/uak/</td><td></td>
      </tr>
      <tr>
        <th>例字</th>
        <td></td><td>法</td><td></td><td>挖</td><td>不</td><td>国</td><td></td>
      </tr>
    </table>
    <h2>声调</h2>
    <table>
      <tr>
        <th></th>
        <th>阴平</th><th>阳平</th><th>上声</th><th>阴去</th><th>阳去</th><th>阴入</th><th>舒入</th><th>阳入</th>
      </tr>
      <tr>
        <th>记号</th>
        <td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td colspan="2">6</td><td>7</td>
      </tr>
      <tr>
        <th>调值</th>
        <td>33</td><td>22</td><td>31</td><td>44</td><td>43</td><td>5</td><td>55</td><td>2</td>
      </tr>
      <tr>
        <th>例字</th>
        <td>诗</td><td>时</td><td>死</td><td>世</td><td>是</td><td>失</td><td>接</td><td>实</td>
      </tr>
    </table>
  </div>
</template>
