<template>
  <div class="pinyin">
    <paper title="拼音">
      <h2>茂名白话</h2>
      <h3>声母</h3>
      <table>
        <tr>
          <th>声母</th>
          <th>b</th>
          <th>p</th>
          <th>m</th>
          <th>f</th>
          <th>d</th>
          <th>t</th>
          <th>n</th>
          <th>l</th>
        </tr>
        <tr>
          <th>音标</th>
          <td>/p/</td>
          <td>/pʰ/</td>
          <td>/m/</td>
          <td>/f/</td>
          <td>/t/</td>
          <td>/tʰ/</td>
          <td>/n/</td>
          <td>/l/</td>
        </tr>
        <tr>
          <th>例字</th>
          <td>波</td>
          <td>坡</td>
          <td>摸</td>
          <td>科</td>
          <td>多</td>
          <td>拖</td>
          <td>挪</td>
          <td>罗</td>
        </tr>
      </table>
      <table>
        <tr>
          <th>声母</th>
          <th>g</th>
          <th>k</th>
          <th>ng</th>
          <th>h</th>
          <th>z</th>
          <th>c</th>
          <th>s</th>
          <th>nj</th>
          <th>sl</th>
          <th>j</th>
          <th>w</th>
        </tr>
        <tr>
          <th>音标</th>
          <td>/k/</td>
          <td>/kʰ/</td>
          <td>/ŋ/</td>
          <td>/h/</td>
          <td>/tʃ/</td>
          <td>/tʃʰ/</td>
          <td>/ʃ/</td>
          <td>/ɳ/</td>
          <td>/ɬ/</td>
          <td>/j/</td>
          <td>/w/</td>
        </tr>
        <tr>
          <th>例字</th>
          <td>哥</td>
          <td>柯</td>
          <td>我</td>
          <td>可</td>
          <td>左</td>
          <td>错</td>
          <td>所</td>
          <td>日</td>
          <td>锁</td>
          <td>也</td>
          <td>话</td>
        </tr>
      </table>
      <h3>韵母</h3>
      <hr>
      <h2>电白黎话</h2>
      <h3>声母</h3>
      <table>
        <tr>
          <th>声母</th>
          <th>b</th>
          <th>p</th>
          <th>m</th>
          <th>w</th>
          <th>d</th>
          <th>t</th>
          <th>n</th>
          <th>l</th>
        </tr>
        <tr>
          <th>音标</th>
          <td>/p/</td>
          <td>/pʰ/</td>
          <td>/m/</td>
          <td>/w/</td>
          <td>/t/</td>
          <td>/tʰ/</td>
          <td>/n/</td>
          <td>/l/</td>
        </tr>
        <tr>
          <th>例字</th>
          <td>波</td>
          <td>坡</td>
          <td>摸</td>
          <td>我</td>
          <td>刀</td>
          <td>桃</td>
          <td>挪</td>
          <td>罗</td>
        </tr>
      </table>
      <table>
        <tr>
          <th>声母</th>
          <th>g</th>
          <th>k</th>
          <th>ng</th>
          <th>h</th>
          <th>z</th>
          <th>c</th>
          <th>sl</th>
          <th>nj</th>
          <th>j</th>
        </tr>
        <tr>
          <th>音标</th>
          <td>/k/</td>
          <td>/kʰ/</td>
          <td>/ŋ/</td>
          <td>/h/</td>
          <td>/tʃ/</td>
          <td>/tʃʰ/</td>
          <td>/ɬ/</td>
          <td>/ɳ/</td>
          <td>/j/</td>
        </tr>
        <tr>
          <th>例字</th>
          <td>稿</td>
          <td>可</td>
          <td>卧</td>
          <td>好</td>
          <td>左</td>
          <td>错</td>
          <td>所</td>
          <td>让</td>
          <td>二</td>
        </tr>
      </table>
      <hr>
      <h2>电白涯话</h2>
      <h3>声母</h3>
      <table>
        <tr>
          <th>声母</th>
          <th>b</th>
          <th>p</th>
          <th>m</th>
          <th>w</th>
          <th>d</th>
          <th>t</th>
          <th>n</th>
          <th>l</th>
        </tr>
        <tr>
          <th>音标</th>
          <td>/p/</td>
          <td>/pʰ/</td>
          <td>/m/</td>
          <td>/w/</td>
          <td>/t/</td>
          <td>/tʰ/</td>
          <td>/n/</td>
          <td>/l/</td>
        </tr>
        <tr>
          <th>例字</th>
          <td>波</td>
          <td>坡</td>
          <td>摸</td>
          <td>我</td>
          <td>刀</td>
          <td>桃</td>
          <td>挪</td>
          <td>罗</td>
        </tr>
      </table>
      <table>
        <tr>
          <th>声母</th>
          <th>g</th>
          <th>k</th>
          <th>ng</th>
          <th>h</th>
          <th>z</th>
          <th>c</th>
          <th>sl</th>
          <th>nj</th>
          <th>j</th>
        </tr>
        <tr>
          <th>音标</th>
          <td>/k/</td>
          <td>/kʰ/</td>
          <td>/ŋ/</td>
          <td>/h/</td>
          <td>/tʃ/</td>
          <td>/tʃʰ/</td>
          <td>/ɬ/</td>
          <td>/ɳ/</td>
          <td>/j/</td>
        </tr>
        <tr>
          <th>例字</th>
          <td>稿</td>
          <td>可</td>
          <td>卧</td>
          <td>好</td>
          <td>左</td>
          <td>错</td>
          <td>所</td>
          <td>让</td>
          <td>二</td>
        </tr>
      </table>
    </paper>
  </div>
</template>

<script>
import paper from '@/components/elements/paper'

export default {
  name: 'pinyin',
  components: {
    paper
  }
}
</script>

<style lang='scss' scoped>
.pinyin {
  min-height: calc(100vh - 110px);
  display: flex;
  flex-direction: column;
  align-items: center;
  background: #ddd;

  .wrapper {
    .inner {

      table {
        margin: 10px 0;
        text-align: center;
        th, td {
          width: 40px;
        }
      }
    }
  }
}
</style>